= Restore Data to Couchbase Database

Backing up data for a Couchbase database is an essential part of Disaster Recovery plan. This ensures that the data can be restored to the last backup in case of a disaster. This quick start guide will show how to restore data using Couchbase Community Edition. https://github.com/couchbase-guides/couchbase-backup[Another guide] shows how to backup data from a Couchbase server.

The https://developer.couchbase.com/documentation/server/current/backup-restore/backup-restore.html[cbrestore] tool in Couchbase Community Edition will be used in this guide.

In addition, Couchbase Enterprise Edition also has the `cbbackupmgr` tool. Complete details about this tool is at https://developer.couchbase.com/documentation/server/current/backup-restore/enterprise-backup-restore.html[cbbackupmgr].

For this guide, Couchbase server is installed using https://github.com/couchbase-guides/couchbase-amazon-cli[Couchbase install on Amazon EC2].

== Restore Data to Couchbase Server

You may like to restore the backed up data on a different server, likely for local testing or development.

Backed up data can be restored to a Couchbase database as:

```
cbrestore \
    -b twitter \
    -B twitter \
    -u <admin-username> \
    -p <admin-password> \
    var/lib/couchbase/backups \
    http://localhost:8091
```

In this command:

. `-b` specify the source bucket
. `-B` specify the destination bucket. Make sure the destination is already created.
. `-u` specify the admin username for the node/cluster
. `-p` specify the admin password for the node/cluster
. `var/lib/couchbase/backups` is the directory extracted from the tar file that contains backup data
. `localhost:8091` is the destination Couchbase host and port

This command will succeed if the source and destination operating systems are Unix. However, on Mac OS, this command will give the following error:

```
2017-01-10 19:50:48,660: s0 error: async operation: error: map missing vbucket_id: 512; perhaps your source does not have vbuckets; if so, try using moxi (HOST:11211) as a destination on sink: http://localhost:8091(twitter@127.0.0.1:8091)
error: map missing vbucket_id: 512; perhaps your source does not have vbuckets; if so, try using moxi (HOST:11211) as a destination
```

This error occurs because Couchbase creates 64 vBuckets on Mac OS and 1024 vBuckets on every where else. The concept of vBuckets is explained at https://developer.couchbase.com/documentation/server/current/concepts/distributed-data-management.html[Couchbase Distributed Data Management]. The database was backed up from a Couchbase database running on Ubuntu and restored on a Couchbase database running on Mac OS. Fixing this error requires to rehash the data correctly from 1024 vBuckets on Ubuntu to 64 vBuckets on Mac OS. 

The option that enables rehashing can be included in the original command. The updated command that restores the data is:

```
cbrestore \
    -b twitter \
    -B twitter 
    var/lib/couchbase/backups \
    http://localhost:8091
    -x rehash=1
```

Complete details about the `cbrestore` command, including all the options, are explained at https://developer.couchbase.com/documentation/server/current/cli/cbrestore-tool.html

